<?= $this->partial('partial_header.phtml'); ?>

<main class="flex-shrink-0">
    <div class="container">
        <h2 class="mt-5">Users</h2>
        <a href="">Create new</a>
        <div class="table-responsive small">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th scope="col">Email</th>
                    <th scope="col">Roles</th>
                    <th scope="col">First name</th>
                    <th scope="col">Last name</th>
                    <th scope="col">actions</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($users as $user) : ?>
                <tr>
                    <td scope="row"><?= $user->getEmail(); ?></td>
                    <td></td>
                    <td><?= $user->getFirstName(); ?></td>
                    <td><?= $user->getLastName(); ?></td>
                    <td>
                        <a href="<?= $this->url('user-view', ['action' => 'view', 'id' => $user->getId()]); ?>"
                           class="btn btn-primary btn-sm">View</a>
                        <a href="<?= $this->url('user-edit', ['action' => 'edit', 'id' => $user->getId()]); ?>"
                           class="btn btn-secondary btn-sm">Edit</a>
                        <a href="<?= $this->url('user-delete', ['action' => 'delete', 'id' => $user->getId()]); ?>"
                           class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>
                <!--{% else %}
                <tr>
                    <td colspan="5">no records found</td>
                </tr>-->
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</main>

<footer class="footer mt-auto py-3 bg-body-tertiary">
    <div class="container">
        <span class="text-body-secondary">Place sticky footer content here.</span>
    </div>
</footer>