<?= $this->partial('partial_header.phtml'); ?>

<!-- Begin page content -->
<main class="flex-shrink-0">

    <div class="container mt-5">
        <h1>User Profile</h1>

        <?php $user = $this->user; ?>

        <ul>
            <li><strong>First Name:</strong> <?= $user->getFirstName(); ?></li>
            <li><strong>Last Name:</strong> <?= $user->getLastName(); ?></li>
            <li><strong>Email:</strong> <?= $user->getEmail(); ?></li>
            <!-- Add more user data as needed -->
        </ul>

    </div>

<main>