<?php
// within a view script
$form = $this->form;
$form->prepare();

// Get the form label plugin
$formLabel = $this->plugin('formLabel');
?>

<!-- Custom styles for this template -->
<style>
    html,
    body {
        height: 100%;
    }

    .form-signin {
        max-width: 330px;
        padding: 1rem;
    }

    .form-signin .form-floating:focus-within {
        z-index: 2;
    }

    .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
    }

    .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }
</style>

<main class="form-signin w-100 m-auto">
    <?php echo $this->form()->openTag($form); ?>

    <img class="mb-4" src="https://getbootstrap.com/docs/5.3/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign up</h1>

    <div class="form-floating">
        <?= $this->formInput($form->get('first_name'), ['id' => 'first_name', 'class' => 'form-control', 'placeholder' => 'First Name', 'required' => 'required']); ?>
        <?= $this->formLabel($form->get('first_name'), 'First Name'); ?>
    </div>

    <div class="form-floating">
        <?= $this->formInput($form->get('last_name'), ['id' => 'last_name', 'class' => 'form-control', 'placeholder' => 'Last Name', 'required' => 'required']); ?>
        <?= $this->formLabel($form->get('last_name'), 'Last Name'); ?>
    </div>

    <div class="form-floating">
        <?= $this->formInput($form->get('email'), ['id' => 'email', 'class' => 'form-control', 'placeholder' => 'Email', 'required' => 'required']); ?>
        <?= $this->formLabel($form->get('email'), 'Email'); ?>
    </div>
    <div class="form-floating">
        <?= $this->formInput($form->get('plainPassword'), ['id' => 'password', 'type' => 'password', 'class' => 'form-control', 'placeholder' => 'Password', 'required' => 'required']); ?>
        <?= $this->formLabel($form->get('plainPassword'), 'Password'); ?>
    </div>

    <input type="hidden" name="_csrf_token" value="">
    <?= $this->formButton($form->get('submit'), 'Sign up'); ?>

    <p class="mt-3">Already have an account? <a href="<?= $this->url('user-login', ['action' => 'login']); ?>">Login</a></p>
    </form>
</main>