<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en" class="h-100" data-bs-theme="auto">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>
        <meta charset="utf-8">
        <meta name="theme-color" content="#712cf9">
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ])
            ->prependStylesheet($this->basePath('build/main.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>

        <?= $this->partial('colour_mode.phtml'); ?>

        <?= $this->content ?>

        <?= $this->inlineScript()->prependFile($this->basePath('build/main.js')) ?>
    </body>
</html>