<?= $this->partial('partial_header.phtml'); ?>

<main class="flex-shrink-0">
    <div class="container mt-5">
        <h2>Role List</h2>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Role Name</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($roles as $role) : ?>
                <tr>
                    <td><?= $this->escapeHtml($role->getName()); ?></td>
                    <td>
                        <!-- Action buttons for editing and deleting -->
                        <a href="<?= $this->url('role-edit', ['id' => $role->getId()]); ?>" class="btn btn-primary btn-sm">Edit</a>
                        <a href="<?= $this->url('role-delete', ['id' => $role->getId()]); ?>" class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

        <a href="<?= $this->url('role-add'); ?>" class="btn btn-primary">Add Role</a>
    </div>
</main>